import type { BrandRamp, GreyRamp } from '../types.js';

/**
 * generates neutral semantic tokens from grey and brand ramps.
 * @param grey grey ramp
 * @param brand brand ramp
 * @returns light and dark neutral token mappings
 */
export function generateNeutralTokens(
	grey: GreyRamp,
	brand: BrandRamp,
): { light: Record<string, string>; dark: Record<string, string> } {
	const light: Record<string, string> = {
		// #region foreground
		colorNeutralForeground1: grey[14],
		colorNeutralForeground1Hover: grey[14],
		colorNeutralForeground1Pressed: grey[14],
		colorNeutralForeground1Selected: grey[14],
		colorNeutralForeground2: grey[26],
		colorNeutralForeground2Hover: grey[14],
		colorNeutralForeground2Pressed: grey[14],
		colorNeutralForeground2Selected: grey[14],
		colorNeutralForeground2BrandHover: brand[80],
		colorNeutralForeground2BrandPressed: brand[70],
		colorNeutralForeground2BrandSelected: brand[80],
		colorNeutralForeground3: grey[38],
		colorNeutralForeground3Hover: grey[26],
		colorNeutralForeground3Pressed: grey[26],
		colorNeutralForeground3Selected: grey[26],
		colorNeutralForeground4: grey[44],
		colorNeutralForeground5: grey[38],
		colorNeutralForeground5Hover: grey[14],
		colorNeutralForeground5Pressed: grey[14],
		colorNeutralForeground5Selected: grey[14],
		colorNeutralForegroundDisabled: grey[74],
		colorNeutralForeground1Static: grey[14],
		colorNeutralForegroundStaticInverted: '#ffffff',
		colorNeutralForegroundInverted: '#ffffff',
		colorNeutralForegroundInvertedHover: '#ffffff',
		colorNeutralForegroundInvertedPressed: '#ffffff',
		colorNeutralForegroundInvertedSelected: '#ffffff',
		colorNeutralForegroundInverted2: '#ffffff',
		colorNeutralForegroundOnBrand: '#ffffff',
		// #endregion

		// #region background
		colorNeutralBackground1: '#ffffff',
		colorNeutralBackground1Hover: grey[96],
		colorNeutralBackground1Pressed: grey[88],
		colorNeutralBackground1Selected: grey[92],
		colorNeutralBackground2: grey[98],
		colorNeutralBackground2Hover: grey[94],
		colorNeutralBackground2Pressed: grey[86],
		colorNeutralBackground2Selected: grey[90],
		colorNeutralBackground3: grey[96],
		colorNeutralBackground3Hover: grey[92],
		colorNeutralBackground3Pressed: grey[84],
		colorNeutralBackground3Selected: grey[88],
		colorNeutralBackground4: grey[94],
		colorNeutralBackground4Hover: grey[98],
		colorNeutralBackground4Pressed: grey[96],
		colorNeutralBackground4Selected: '#ffffff',
		colorNeutralBackground5: grey[92],
		colorNeutralBackground5Hover: grey[96],
		colorNeutralBackground5Pressed: grey[94],
		colorNeutralBackground5Selected: grey[98],
		colorNeutralBackground6: grey[90],
		colorNeutralBackgroundAlpha: 'rgba(255, 255, 255, 0.5)',
		colorNeutralBackgroundAlpha2: 'rgba(255, 255, 255, 0.8)',
		colorNeutralBackgroundDisabled: grey[94],
		colorNeutralBackgroundInverted: grey[16],
		colorNeutralBackgroundInvertedHover: grey[24],
		colorNeutralBackgroundInvertedPressed: grey[12],
		colorNeutralBackgroundInvertedSelected: grey[22],
		colorNeutralBackgroundStatic: grey[20],
		colorSubtleBackground: 'transparent',
		colorSubtleBackgroundHover: grey[96],
		colorSubtleBackgroundPressed: grey[88],
		colorSubtleBackgroundSelected: grey[92],
		colorSubtleBackgroundLightAlphaHover: 'rgba(255, 255, 255, 0.7)',
		colorSubtleBackgroundLightAlphaPressed: 'rgba(255, 255, 255, 0.5)',
		colorSubtleBackgroundLightAlphaSelected: 'transparent',
		colorSubtleBackgroundInverted: 'transparent',
		colorSubtleBackgroundInvertedHover: 'rgba(0, 0, 0, 0.1)',
		colorSubtleBackgroundInvertedPressed: 'rgba(0, 0, 0, 0.3)',
		colorSubtleBackgroundInvertedSelected: 'rgba(0, 0, 0, 0.2)',
		colorTransparentBackground: 'transparent',
		colorTransparentBackgroundHover: 'transparent',
		colorTransparentBackgroundPressed: 'transparent',
		colorTransparentBackgroundSelected: 'transparent',
		// #endregion

		// #region stroke
		colorNeutralStroke1: grey[82],
		colorNeutralStroke1Hover: grey[78],
		colorNeutralStroke1Pressed: grey[70],
		colorNeutralStroke1Selected: grey[74],
		colorNeutralStroke2: grey[88],
		colorNeutralStroke3: grey[94],
		colorNeutralStrokeSubtle: grey[88],
		colorNeutralStrokeOnBrand: '#ffffff',
		colorNeutralStrokeOnBrand2: '#ffffff',
		colorNeutralStrokeOnBrand2Hover: '#ffffff',
		colorNeutralStrokeOnBrand2Pressed: '#ffffff',
		colorNeutralStrokeOnBrand2Selected: '#ffffff',
		colorNeutralStrokeDisabled: grey[88],
		colorNeutralStrokeInvertedDisabled: 'rgba(255, 255, 255, 0.4)',
		colorNeutralStrokeAccessible: grey[38],
		colorNeutralStrokeAccessibleHover: grey[34],
		colorNeutralStrokeAccessiblePressed: grey[30],
		colorNeutralStrokeAccessibleSelected: brand[80],
		colorNeutralStrokeAlpha: 'rgba(0, 0, 0, 0.05)',
		colorNeutralStrokeAlpha2: 'rgba(255, 255, 255, 0.2)',
		colorTransparentStroke: 'transparent',
		colorTransparentStrokeInteractive: 'transparent',
		colorTransparentStrokeDisabled: 'transparent',
		// #endregion

		// #region overlay & focus
		colorBackgroundOverlay: 'rgba(0, 0, 0, 0.4)',
		colorScrollbarOverlay: 'rgba(0, 0, 0, 0.5)',
		colorStrokeFocus1: '#ffffff',
		colorStrokeFocus2: '#000000',
		// #endregion

		// #region shadow
		colorNeutralShadowAmbient: 'rgba(0, 0, 0, 0.12)',
		colorNeutralShadowKey: 'rgba(0, 0, 0, 0.14)',
		colorNeutralShadowAmbientLighter: 'rgba(0, 0, 0, 0.06)',
		colorNeutralShadowKeyLighter: 'rgba(0, 0, 0, 0.07)',
		colorNeutralShadowAmbientDarker: 'rgba(0, 0, 0, 0.2)',
		colorNeutralShadowKeyDarker: 'rgba(0, 0, 0, 0.24)',
		// #endregion
	};

	const dark: Record<string, string> = {
		// #region foreground
		colorNeutralForeground1: '#ffffff',
		colorNeutralForeground1Hover: '#ffffff',
		colorNeutralForeground1Pressed: '#ffffff',
		colorNeutralForeground1Selected: '#ffffff',
		colorNeutralForeground2: grey[84],
		colorNeutralForeground2Hover: '#ffffff',
		colorNeutralForeground2Pressed: '#ffffff',
		colorNeutralForeground2Selected: '#ffffff',
		colorNeutralForeground2BrandHover: brand[100],
		colorNeutralForeground2BrandPressed: brand[90],
		colorNeutralForeground2BrandSelected: brand[100],
		colorNeutralForeground3: grey[68],
		colorNeutralForeground3Hover: grey[84],
		colorNeutralForeground3Pressed: grey[84],
		colorNeutralForeground3Selected: grey[84],
		colorNeutralForeground4: grey[60],
		colorNeutralForeground5: grey[68],
		colorNeutralForeground5Hover: '#ffffff',
		colorNeutralForeground5Pressed: '#ffffff',
		colorNeutralForeground5Selected: '#ffffff',
		colorNeutralForegroundDisabled: grey[36],
		colorNeutralForeground1Static: grey[14],
		colorNeutralForegroundStaticInverted: '#ffffff',
		colorNeutralForegroundInverted: grey[14],
		colorNeutralForegroundInvertedHover: grey[14],
		colorNeutralForegroundInvertedPressed: grey[14],
		colorNeutralForegroundInvertedSelected: grey[14],
		colorNeutralForegroundInverted2: grey[14],
		colorNeutralForegroundOnBrand: '#ffffff',
		// #endregion

		// #region background
		colorNeutralBackground1: grey[16],
		colorNeutralBackground1Hover: grey[24],
		colorNeutralBackground1Pressed: grey[12],
		colorNeutralBackground1Selected: grey[22],
		colorNeutralBackground2: grey[12],
		colorNeutralBackground2Hover: grey[20],
		colorNeutralBackground2Pressed: grey[8],
		colorNeutralBackground2Selected: grey[18],
		colorNeutralBackground3: grey[8],
		colorNeutralBackground3Hover: grey[16],
		colorNeutralBackground3Pressed: grey[4],
		colorNeutralBackground3Selected: grey[14],
		colorNeutralBackground4: grey[4],
		colorNeutralBackground4Hover: grey[12],
		colorNeutralBackground4Pressed: '#000000',
		colorNeutralBackground4Selected: grey[10],
		colorNeutralBackground5: '#000000',
		colorNeutralBackground5Hover: grey[8],
		colorNeutralBackground5Pressed: grey[2],
		colorNeutralBackground5Selected: grey[6],
		colorNeutralBackground6: grey[20],
		colorNeutralBackgroundAlpha: 'rgba(26, 26, 26, 0.5)',
		colorNeutralBackgroundAlpha2: 'rgba(26, 26, 26, 0.7)',
		colorNeutralBackgroundDisabled: grey[8],
		colorNeutralBackgroundInverted: '#ffffff',
		colorNeutralBackgroundInvertedHover: grey[96],
		colorNeutralBackgroundInvertedPressed: grey[88],
		colorNeutralBackgroundInvertedSelected: grey[92],
		colorNeutralBackgroundStatic: grey[24],
		colorSubtleBackground: 'transparent',
		colorSubtleBackgroundHover: grey[22],
		colorSubtleBackgroundPressed: grey[18],
		colorSubtleBackgroundSelected: grey[20],
		colorSubtleBackgroundLightAlphaHover: 'rgba(255, 255, 255, 0.1)',
		colorSubtleBackgroundLightAlphaPressed: 'rgba(255, 255, 255, 0.05)',
		colorSubtleBackgroundLightAlphaSelected: 'transparent',
		colorSubtleBackgroundInverted: 'transparent',
		colorSubtleBackgroundInvertedHover: 'rgba(0, 0, 0, 0.1)',
		colorSubtleBackgroundInvertedPressed: 'rgba(0, 0, 0, 0.3)',
		colorSubtleBackgroundInvertedSelected: 'rgba(0, 0, 0, 0.2)',
		colorTransparentBackground: 'transparent',
		colorTransparentBackgroundHover: 'transparent',
		colorTransparentBackgroundPressed: 'transparent',
		colorTransparentBackgroundSelected: 'transparent',
		// #endregion

		// #region stroke
		colorNeutralStroke1: grey[40],
		colorNeutralStroke1Hover: grey[46],
		colorNeutralStroke1Pressed: grey[42],
		colorNeutralStroke1Selected: grey[44],
		colorNeutralStroke2: grey[32],
		colorNeutralStroke3: grey[24],
		colorNeutralStrokeSubtle: grey[4],
		colorNeutralStrokeOnBrand: grey[16],
		colorNeutralStrokeOnBrand2: '#ffffff',
		colorNeutralStrokeOnBrand2Hover: '#ffffff',
		colorNeutralStrokeOnBrand2Pressed: '#ffffff',
		colorNeutralStrokeOnBrand2Selected: '#ffffff',
		colorNeutralStrokeDisabled: grey[26],
		colorNeutralStrokeInvertedDisabled: 'rgba(255, 255, 255, 0.4)',
		colorNeutralStrokeAccessible: grey[68],
		colorNeutralStrokeAccessibleHover: grey[74],
		colorNeutralStrokeAccessiblePressed: grey[70],
		colorNeutralStrokeAccessibleSelected: brand[100],
		colorNeutralStrokeAlpha: 'rgba(255, 255, 255, 0.1)',
		colorNeutralStrokeAlpha2: 'rgba(255, 255, 255, 0.2)',
		colorTransparentStroke: 'transparent',
		colorTransparentStrokeInteractive: 'transparent',
		colorTransparentStrokeDisabled: 'transparent',
		// #endregion

		// #region overlay & focus
		colorBackgroundOverlay: 'rgba(0, 0, 0, 0.5)',
		colorScrollbarOverlay: 'rgba(255, 255, 255, 0.6)',
		colorStrokeFocus1: '#000000',
		colorStrokeFocus2: '#ffffff',
		// #endregion

		// #region shadow
		colorNeutralShadowAmbient: 'rgba(0, 0, 0, 0.24)',
		colorNeutralShadowKey: 'rgba(0, 0, 0, 0.28)',
		colorNeutralShadowAmbientLighter: 'rgba(0, 0, 0, 0.12)',
		colorNeutralShadowKeyLighter: 'rgba(0, 0, 0, 0.14)',
		colorNeutralShadowAmbientDarker: 'rgba(0, 0, 0, 0.4)',
		colorNeutralShadowKeyDarker: 'rgba(0, 0, 0, 0.48)',
		// #endregion
	};

	return { light, dark };
}
