import { formatHex, hsv as toHsv, type Hsv } from 'culori';
import { convertHsvToRgb } from 'culori/fn';

import type { BrandRamp, ColorRamp } from './types.js';

/**
 * generates a color ramp with 12 stops from a base color.
 * shades are generated by reducing value, tints by reducing saturation and expanding value.
 * @param baseColor base color in hex format
 * @returns color ramp with shade50-shade10, primary, tint10-tint60
 */
export function generateColorRamp(baseColor: string): ColorRamp {
	const hsv = toHsv(baseColor);
	if (!hsv) {
		throw new Error(`invalid color: ${baseColor}`);
	}

	// shade factors: [0.1, 0.24, 0.44, 0.7, 0.84] for shade10-shade50
	const shadeFactors = [0.1, 0.24, 0.44, 0.7, 0.84];
	// tint factors: [0.12, 0.24, 0.4, 0.7, 0.84, 0.96] for tint10-tint60
	const tintFactors = [0.12, 0.24, 0.4, 0.7, 0.84, 0.96];

	const shades = shadeFactors.map((factor) => generateShade(hsv, factor));
	const tints = tintFactors.map((factor) => generateTint(hsv, factor));

	return {
		shade50: shades[4],
		shade40: shades[3],
		shade30: shades[2],
		shade20: shades[1],
		shade10: shades[0],
		primary: formatHex(hsv)!,
		tint10: tints[0],
		tint20: tints[1],
		tint30: tints[2],
		tint40: tints[3],
		tint50: tints[4],
		tint60: tints[5],
	};
}

/**
 * generates a brand ramp with 16 stops from a base color.
 * positions 10-160 in steps of 10.
 * @param baseColor base color in hex format
 * @returns brand ramp keyed by position (10-160)
 */
export function generateBrandRamp(baseColor: string): BrandRamp {
	const hsv = toHsv(baseColor);
	if (!hsv) {
		throw new Error(`invalid color: ${baseColor}`);
	}

	const ramp: BrandRamp = {};

	// positions 10-80 are shades (darker), 80 is primary, 90-160 are tints (lighter)
	// shade factors mapped to positions 10-70 (7 shades)
	// position 80 = primary
	// tint factors mapped to positions 90-160 (8 tints)

	// shade factors for positions 10-70 (darkest to lightest shade)
	const shadeFactors: Record<number, number> = {
		10: 0.96,
		20: 0.84,
		30: 0.7,
		40: 0.52,
		50: 0.36,
		60: 0.24,
		70: 0.12,
	};

	// tint factors for positions 90-160 (lightest to most faded)
	const tintFactors: Record<number, number> = {
		90: 0.08,
		100: 0.16,
		110: 0.28,
		120: 0.4,
		130: 0.52,
		140: 0.68,
		150: 0.84,
		160: 0.96,
	};

	for (let i = 10; i <= 70; i += 10) {
		ramp[i] = generateShade(hsv, shadeFactors[i]);
	}

	ramp[80] = formatHex(hsv)!;

	for (let i = 90; i <= 160; i += 10) {
		ramp[i] = generateTint(hsv, tintFactors[i]);
	}

	return ramp;
}

/**
 * generates a shade (darker) by reducing value.
 */
function generateShade(hsv: Hsv, factor: number): string {
	const shaded: Hsv = {
		mode: 'hsv',
		h: hsv.h,
		s: hsv.s,
		v: (hsv.v ?? 1) * (1 - factor),
	};
	return formatHex(convertHsvToRgb(shaded))!;
}

/**
 * generates a tint (lighter) by reducing saturation and expanding value.
 */
function generateTint(hsv: Hsv, factor: number): string {
	const v = hsv.v ?? 1;
	const tinted: Hsv = {
		mode: 'hsv',
		h: hsv.h,
		s: (hsv.s ?? 0) * (1 - factor),
		v: v + (1 - v) * factor,
	};
	return formatHex(convertHsvToRgb(tinted))!;
}
